In [1]:
from scipy import sparse
from scipy.stats import uniform  # create uniform random numbers
import numpy as np

In [13]:
mat = np.array([
    [1., 0., 0., 0., 0.],
    [0., 0., 2., 0., 3.],
    [0., 0., 0., 0., 0.],
    [0., 0., 0., 4., 0.],
    [0., 0., 0., 0., 5.]
])

## `coo_matrix` (coordinate sparse matrix)

In [19]:
mat_coo = sparse.coo_matrix(mat)
print(mat_coo)

  (0, 0)	1.0
  (1, 2)	2.0
  (1, 4)	3.0
  (3, 3)	4.0
  (4, 4)	5.0


In [21]:
# internal representation

print(mat_coo.data)
print(mat_coo.row)
print(mat_coo.col)

[1. 2. 3. 4. 5.]
[0 1 1 3 4]
[0 2 4 3 4]


In [7]:
mat_coo.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 0., 2., 0., 3.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

## `csc_matrix` (compressed sparse column)

In [18]:
mat_csc = sparse.csc_matrix(mat)
print(mat_csc)

  (0, 0)	1.0
  (1, 2)	2.0
  (3, 3)	4.0
  (1, 4)	3.0
  (4, 4)	5.0


In [20]:
# internal representation

print(mat_csc.data)
print(mat_csc.indptr)
print(mat_csc.indices)

[1. 2. 4. 3. 5.]
[0 1 1 2 3 5]
[0 1 3 1 4]


## `csr_matrix` (compressed sparse row)

In [22]:
mat_csr = sparse.csr_matrix(mat)
print(mat_csr)

  (0, 0)	1.0
  (1, 2)	2.0
  (1, 4)	3.0
  (3, 3)	4.0
  (4, 4)	5.0


In [23]:
# internal representation

print(mat_csr.data)
print(mat_csr.indptr)
print(mat_csr.indices)

[1. 2. 3. 4. 5.]
[0 1 3 3 4 5]
[0 2 4 3 4]
